title: Javier Cadiz Blog

permalink: /posts/:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

# Metadata
author:
  name: Javier Cadiz
  bio: Hi, I'm Javier! I build apps and like to work with differents stacks.
  picture: http://s.gravatar.com/avatar/82741364f990c62042e88b3b9334b024
  twitter: cadizjavier
  github: cadizjavier
  stackoverflow: http://stackoverflow.com/users/1373105/javier-cadiz
