title: Javier Cadiz
permalink: /posts/:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

# Metadata
author:
  name: Javier Cadiz
  picture: https://s.gravatar.com/avatar/82741364f990c62042e88b3b9334b024
